(function(){var R=window.$R;var EXPAND_KEY='RANDOM3E7C2B50D64611DDB4810';var TYPE_ELEMENT=1,TYPE_COMMENT=8,TYPE_DOCUMENT=9;R.extend(R,{domOps:function(target,newElements,reverse,cb){var elems=newElements;var count=0;if(reverse){elems=R.castToArray(elems);elems.reverse();elems=R(elems);}
R.each(target,function(e){if(count++){elems=elems.clone();}
R.each(elems,function(n){cb(e,n);});});},isTabletBehavior:function(){return window.navigator.userAgent.match(/(iPad|Android)/i);}
});R.extend(R.prototype,{nextSibling:function(spec){if(this.length<=0)return R([]);var elem=this[0];for(var n=elem['nextSibling'];n&&n!=document;n=n['nextSibling']){if(n.nodeType==TYPE_ELEMENT)return R(n);}
return R([]);},previousSibling:function(){if(this.length<=0)return R([]);var elem=this[0];for(var n=elem['previousSibling'];n&&n!=document;n=n['previousSibling']){if(n.nodeType==TYPE_ELEMENT)return R(n);}
return R([]);},parent:function(spec){return this.eachAndMerge(function(e){return R.filter([e.parentNode],spec||'*');});},parents:function(spec){return this.eachAndMerge(function(e){return R.filter(R.walk(e,'parentNode'),spec||'*');});},parentsAndMe:function(spec){return this.eachAndMerge(function(e){return R.filter(R.merge(R.walk(e,'parentNode'),[e]),spec||'*');});},children:function(spec){return this.eachAndMerge(function(e){return R.filter(R.grep(e.childNodes,function(ce){return ce.nodeType==TYPE_ELEMENT;}),spec||'*'
);}
);},remove:function(){R.each(this,function(e){R('*',e).each(function(){R.event.unbind(this);R.removeData(this);});R.event.unbind(e);R.removeData(e);if(e.parentNode)e.parentNode.removeChild(e);});},empty:function(){R.each(this,function(e){R('*>*',e).remove();while(e.lastChild)e.removeChild(e.lastChild);});return this;},clone:function(){var ret=this.map(function(){return this.cloneNode(true);});ret.find("*").removeAttr(EXPAND_KEY);ret.removeAttr(EXPAND_KEY);return ret;},appendTo:function(spec){R.domOps(R(spec),this,0,function(e,n){e.appendChild(n);});return this;},prependTo:function(spec){R.domOps(R(spec),this,1,function(e,n){e.firstChild?e.insertBefore(n,e.firstChild):e.appendChild(n);});return this;},append:function(spec){R.domOps(this,R(spec),0,function(e,n){e.appendChild(n);});return this;},prepend:function(spec){R.domOps(this,R(spec),1,function(e,n){e.insertBefore(n,e.firstChild);});return this;},text:function(text){if(arguments.length==0){var ret='';var fnLoop,fnValue;fnLoop=function(e){R.each(e.childNodes,fnValue);};fnValue=function(e){if(e.nodeType!=TYPE_COMMENT){if(e.nodeType!=TYPE_ELEMENT){ret+=e.nodeValue;}else{fnLoop(e);}
}
};R.each(this,fnLoop);return ret;}else if(this.length>0){if(text!=null&&typeof text!="object"){this.empty().append((this[0].ownerDocument||document).createTextNode(text||''));}else{throw'The text to be added must be a string';}
return this;}
},bind:function(type,cb){R.each(this,function(e){R.event.bind(e,type,cb);});return this;},unbind:function(type,cb){R.each(this,function(e){R.event.unbind(e,type,cb);});return this;},one:function(type,cb){var wrapper=function(e){R(this).unbind(type,wrapper);return cb.apply(this,arguments);};R.event.cloneId(wrapper,cb);R.each(this,function(e){R.event.bind(e,type,wrapper);});return this;},trigger:function(type){R.each(this,function(e){R.event.trigger(type,e);});return this;},triggerHandler:function(type){R.each(this,function(e){R.event.trigger(type,e,true);});return this;}
});})();